apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - platform-config.yaml
  - apps/order-service.yaml
  - apps/payment-service.yaml
  - apps/notification-service.yaml
