apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
  namespace: ms-ddd-kafka
type: Opaque
stringData:
  # Replace with ExternalSecrets/SealedSecrets/etc in real prod.
  DATABASE_URL: postgresql://orders_user:CHANGE_ME@orders-postgresql:5432/orders_db
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-db-secret
  namespace: ms-ddd-kafka
type: Opaque
stringData:
  DATABASE_URL: postgresql://payments_user:CHANGE_ME@payments-postgresql:5432/payments_db
