fullnameOverride: kafka

# PoC-friendly defaults
controller:
  replicaCount: 1
broker:
  replicaCount: 1

# Plaintext inside the cluster for local dev
listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT

# Disable auth for kind
sasl:
  enabledMechanisms: ""
  interBrokerMechanism: ""
  controllerMechanism: ""

tls:
  type: PEM
  enabled: false

# Keep storage ephemeral for kind
persistence:
  enabled: false
